name: Gradle
on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
jobs:
  check:
    strategy:
      matrix:
        entry:
          - { opensearch-version: 1.3.6, java-version: 11 }
          - { opensearch-version: 1.3.6, java-version: 17 }
          - { opensearch-version: 1.3.6, java-version: 19 }
          - { opensearch-version: 2.3.0, java-version: 11 }
          - { opensearch-version: 2.3.0, java-version: 17 }
          - { opensearch-version: 2.3.0, java-version: 19 }
        runs-on: [ubuntu-latest]
    name: Check on ${{ matrix.runs-on }} (JDK-${{ matrix.entry.java-version }}, OpenSearch ${{ matrix.entry.opensearch-version }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.entry.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.entry.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Check and Test with Gradle
        if: ${{ matrix.runs-on == 'ubuntu-latest' }}
        run: ./gradlew check -Popensearch.testcontainers.image-version=${{ matrix.entry.opensearch-version }}
  build:
    strategy:
      matrix:
        java-version: [ 11, 17, 19 ]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    name: Build on ${{ matrix.runs-on }} with jdk ${{ matrix.java-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js and semantic-release plugins
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0
      - run: npm install -g semantic-release@18.0.1 @semantic-release/github@8.0.4 @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: npx semantic-release
        