name: Gradle
on:
  push:
    branches:
      - main
      - beta
jobs:
#  check:
#    strategy:
#      matrix:
#        entry:
##          - { opensearch-version: 1.3.6, java-version: 19 }
##          - { opensearch-version: 2.3.0, java-version: 19 }
##          - { opensearch-version: 1.3.16, java-version: 11 }
##          - { opensearch-version: 1.3.16, java-version: 17 }
##          - { opensearch-version: 2.13.0, java-version: 11 }
##          - { opensearch-version: 2.13.0, java-version: 17 }
#          - { opensearch-version: 2.13.0, java-version: 21 }
#        runs-on: [ubuntu-latest]
#    name: Check on ${{ matrix.runs-on }} (JDK-${{ matrix.entry.java-version }}, OpenSearch ${{ matrix.entry.opensearch-version }})
#    runs-on: ${{ matrix.runs-on }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Set up JDK ${{ matrix.entry.java-version }}
#        uses: actions/setup-java@v3
#        with:
#          java-version: ${{ matrix.entry.java-version }}
#          distribution: 'temurin'
#          cache: gradle
#      - name: Check and Test with Gradle
#        if: ${{ matrix.runs-on == 'ubuntu-latest' }}
#        run: ./gradlew check -Popensearch.testcontainers.image-version=${{ matrix.entry.opensearch-version }}
  build:
    strategy:
      matrix:
        java-version: [ 21 ]
        runs-on: [ubuntu-latest]
    name: Build on ${{ matrix.runs-on }} with jdk ${{ matrix.java-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and semantic-release plugins
        uses: actions/setup-node@v4
      - run: npm install -g semantic-release@21.0.5 @semantic-release/github@8.1.0 @semantic-release/changelog@6.0.2 @semantic-release/commit-analyzer@10.0.2 @semantic-release/exec@6.0.3 @semantic-release/git@10.0.1 @semantic-release/release-notes-generator@11.0.4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        